version: '3.8'

services:

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Mapping the MongoDB default port to host machine
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/opt/mongo/data/db  # Persist MongoDB data to a volume

  spark-history-server:
    build:
      context: quickstart
    command: "/opt/spark/sbin/start-history-server.sh"
    volumes:
      - spark-logs:/opt/spark/spark-events

  main:
    build:
      context: quickstart
    command: "tail -f /dev/null"
    ports:
      - "4040:4040"
    environment:
      - USER=root
      - SPARK_SUBMIT_PATH=spark-submit
      - PYTHONPATH=/srv/chronon
      - SPARK_VERSION=3.1.1
      - JOB_MODE=local[*]
      - PARALLELISM=2
      - EXECUTOR_MEMORY=2G
      - EXECUTOR_CORES=4
      - DRIVER_MEMORY=1G
      - CHRONON_ONLINE_CLASS=ai.chronon.quickstart.online.ChrononMongoOnlineImpl
      - CHRONON_ONLINE_ARGS="-Zuser=admin -Zpassword=admin -Zhost=mongodb -Zport=27017 -Zdatabase=admin"
    volumes:
      - ./api/py/test/sample:/srv/chronon
      - spark-logs:/opt/spark/spark-events
      - ./quickstart/mongo-online-impl:/srv/onlineImpl
      - ./quickstart/jars:/srv/jars

volumes:
  spark-logs:
  mongodb_data:  # Named volume for MongoDB data persistence
