version: '3.8'

services:
  main:
    build:
      context: quickstart
    command: "tail -f /dev/null"
    ports:
      - "4040:4040"
    environment:
      - USER=root
      - SPARK_SUBMIT_PATH=spark-submit
      - PYTHONPATH=/srv/chronon
      - SPARK_VERSION=3.1.1
      - JOB_MODE=local[*]
      - PARALLELISM=2
      - EXECUTOR_MEMORY=2G
      - EXECUTOR_CORES=4
      - DRIVER_MEMORY=1G
    volumes:
      - ./api/py/test/sample:/srv/chronon
      - spark-logs:/opt/spark/spark-events

volumes:
  spark-logs:
  spark-data:
