repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        require_serial: true
        types_or:
        - python
        - pyi
      - id: isort
        name: isort
        language: system
        entry: isort
        require_serial: true
        types_or:
        - python
        - pyi
        args: [--profile=black]
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [ python ]
        args:
          - "--in-place"
          - "--remove-unused-variables"
          - "--expand-star-imports"
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
          - "--remove-duplicate-keys"
