/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ai.chronon.api;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2024-12-31")
public enum Accuracy implements org.apache.thrift.TEnum {
  TEMPORAL(0),
  SNAPSHOT(1);

  private final int value;

  private Accuracy(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Accuracy findByValue(int value) { 
    switch (value) {
      case 0:
        return TEMPORAL;
      case 1:
        return SNAPSHOT;
      default:
        return null;
    }
  }
}
