/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ai.chronon.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * Staging Query encapsulates arbitrary spark computation. One key feature is that the computation follows a
 * "fill-what's-missing" pattern. Basically instead of explicitly specifying dates you specify two macros.
 * `{{ start_date }}` and `{{end_date}}`. Chronon will pass in earliest-missing-partition for `start_date` and
 * execution-date / today for `end_date`. So the query will compute multiple partitions at once.
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2024-12-31")
public class StagingQuery implements org.apache.thrift.TBase<StagingQuery, StagingQuery._Fields>, java.io.Serializable, Cloneable, Comparable<StagingQuery> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StagingQuery");

  private static final org.apache.thrift.protocol.TField META_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("metaData", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField QUERY_FIELD_DESC = new org.apache.thrift.protocol.TField("query", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField START_PARTITION_FIELD_DESC = new org.apache.thrift.protocol.TField("startPartition", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField SETUPS_FIELD_DESC = new org.apache.thrift.protocol.TField("setups", org.apache.thrift.protocol.TType.LIST, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new StagingQueryStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new StagingQueryTupleSchemeFactory();

  /**
   * Contains name, team, output_namespace, execution parameters etc. Things that don't change the semantics of the computation itself.
   * 
   */
  public @org.apache.thrift.annotation.Nullable MetaData metaData; // optional
  /**
   * Arbitrary spark query that should be written with `{{ start_date }}`, `{{ end_date }}` and `{{ latest_date }}` templates
   *      - `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
   *      - `{{ end_date }}` is the end partition of the computing range.
   *      - `{{ latest_date }}` is the end partition independent of the computing range (meant for cumulative sources).
   *      - `{{ max_date(table=namespace.my_table) }}` is the max partition available for a given table.
   * 
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String query; // optional
  /**
   * on the first run, `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
   * 
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String startPartition; // optional
  /**
   * Spark SQL setup statements. Used typically to register UDFs.
   * 
   */
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> setups; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * Contains name, team, output_namespace, execution parameters etc. Things that don't change the semantics of the computation itself.
     * 
     */
    META_DATA((short)1, "metaData"),
    /**
     * Arbitrary spark query that should be written with `{{ start_date }}`, `{{ end_date }}` and `{{ latest_date }}` templates
     *      - `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
     *      - `{{ end_date }}` is the end partition of the computing range.
     *      - `{{ latest_date }}` is the end partition independent of the computing range (meant for cumulative sources).
     *      - `{{ max_date(table=namespace.my_table) }}` is the max partition available for a given table.
     * 
     */
    QUERY((short)2, "query"),
    /**
     * on the first run, `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
     * 
     */
    START_PARTITION((short)3, "startPartition"),
    /**
     * Spark SQL setup statements. Used typically to register UDFs.
     * 
     */
    SETUPS((short)4, "setups");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // META_DATA
          return META_DATA;
        case 2: // QUERY
          return QUERY;
        case 3: // START_PARTITION
          return START_PARTITION;
        case 4: // SETUPS
          return SETUPS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.META_DATA,_Fields.QUERY,_Fields.START_PARTITION,_Fields.SETUPS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.META_DATA, new org.apache.thrift.meta_data.FieldMetaData("metaData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "MetaData")));
    tmpMap.put(_Fields.QUERY, new org.apache.thrift.meta_data.FieldMetaData("query", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.START_PARTITION, new org.apache.thrift.meta_data.FieldMetaData("startPartition", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SETUPS, new org.apache.thrift.meta_data.FieldMetaData("setups", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StagingQuery.class, metaDataMap);
  }

  public StagingQuery() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StagingQuery(StagingQuery other) {
    if (other.isSetMetaData()) {
      this.metaData = new MetaData(other.metaData);
    }
    if (other.isSetQuery()) {
      this.query = other.query;
    }
    if (other.isSetStartPartition()) {
      this.startPartition = other.startPartition;
    }
    if (other.isSetSetups()) {
      java.util.List<java.lang.String> __this__setups = new java.util.ArrayList<java.lang.String>(other.setups);
      this.setups = __this__setups;
    }
  }

  public StagingQuery deepCopy() {
    return new StagingQuery(this);
  }

  @Override
  public void clear() {
    this.metaData = null;
    this.query = null;
    this.startPartition = null;
    this.setups = null;
  }

  /**
   * Contains name, team, output_namespace, execution parameters etc. Things that don't change the semantics of the computation itself.
   * 
   */
  @org.apache.thrift.annotation.Nullable
  public MetaData getMetaData() {
    return this.metaData;
  }

  /**
   * Contains name, team, output_namespace, execution parameters etc. Things that don't change the semantics of the computation itself.
   * 
   */
  public StagingQuery setMetaData(@org.apache.thrift.annotation.Nullable MetaData metaData) {
    this.metaData = metaData;
    return this;
  }

  public void unsetMetaData() {
    this.metaData = null;
  }

  /** Returns true if field metaData is set (has been assigned a value) and false otherwise */
  public boolean isSetMetaData() {
    return this.metaData != null;
  }

  public void setMetaDataIsSet(boolean value) {
    if (!value) {
      this.metaData = null;
    }
  }

  /**
   * Arbitrary spark query that should be written with `{{ start_date }}`, `{{ end_date }}` and `{{ latest_date }}` templates
   *      - `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
   *      - `{{ end_date }}` is the end partition of the computing range.
   *      - `{{ latest_date }}` is the end partition independent of the computing range (meant for cumulative sources).
   *      - `{{ max_date(table=namespace.my_table) }}` is the max partition available for a given table.
   * 
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getQuery() {
    return this.query;
  }

  /**
   * Arbitrary spark query that should be written with `{{ start_date }}`, `{{ end_date }}` and `{{ latest_date }}` templates
   *      - `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
   *      - `{{ end_date }}` is the end partition of the computing range.
   *      - `{{ latest_date }}` is the end partition independent of the computing range (meant for cumulative sources).
   *      - `{{ max_date(table=namespace.my_table) }}` is the max partition available for a given table.
   * 
   */
  public StagingQuery setQuery(@org.apache.thrift.annotation.Nullable java.lang.String query) {
    this.query = query;
    return this;
  }

  public void unsetQuery() {
    this.query = null;
  }

  /** Returns true if field query is set (has been assigned a value) and false otherwise */
  public boolean isSetQuery() {
    return this.query != null;
  }

  public void setQueryIsSet(boolean value) {
    if (!value) {
      this.query = null;
    }
  }

  /**
   * on the first run, `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
   * 
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStartPartition() {
    return this.startPartition;
  }

  /**
   * on the first run, `{{ start_date }}` will be set to this user provided start date, future incremental runs will set it to the latest existing partition + 1 day.
   * 
   */
  public StagingQuery setStartPartition(@org.apache.thrift.annotation.Nullable java.lang.String startPartition) {
    this.startPartition = startPartition;
    return this;
  }

  public void unsetStartPartition() {
    this.startPartition = null;
  }

  /** Returns true if field startPartition is set (has been assigned a value) and false otherwise */
  public boolean isSetStartPartition() {
    return this.startPartition != null;
  }

  public void setStartPartitionIsSet(boolean value) {
    if (!value) {
      this.startPartition = null;
    }
  }

  public int getSetupsSize() {
    return (this.setups == null) ? 0 : this.setups.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getSetupsIterator() {
    return (this.setups == null) ? null : this.setups.iterator();
  }

  public void addToSetups(java.lang.String elem) {
    if (this.setups == null) {
      this.setups = new java.util.ArrayList<java.lang.String>();
    }
    this.setups.add(elem);
  }

  /**
   * Spark SQL setup statements. Used typically to register UDFs.
   * 
   */
  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getSetups() {
    return this.setups;
  }

  /**
   * Spark SQL setup statements. Used typically to register UDFs.
   * 
   */
  public StagingQuery setSetups(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> setups) {
    this.setups = setups;
    return this;
  }

  public void unsetSetups() {
    this.setups = null;
  }

  /** Returns true if field setups is set (has been assigned a value) and false otherwise */
  public boolean isSetSetups() {
    return this.setups != null;
  }

  public void setSetupsIsSet(boolean value) {
    if (!value) {
      this.setups = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case META_DATA:
      if (value == null) {
        unsetMetaData();
      } else {
        setMetaData((MetaData)value);
      }
      break;

    case QUERY:
      if (value == null) {
        unsetQuery();
      } else {
        setQuery((java.lang.String)value);
      }
      break;

    case START_PARTITION:
      if (value == null) {
        unsetStartPartition();
      } else {
        setStartPartition((java.lang.String)value);
      }
      break;

    case SETUPS:
      if (value == null) {
        unsetSetups();
      } else {
        setSetups((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case META_DATA:
      return getMetaData();

    case QUERY:
      return getQuery();

    case START_PARTITION:
      return getStartPartition();

    case SETUPS:
      return getSetups();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case META_DATA:
      return isSetMetaData();
    case QUERY:
      return isSetQuery();
    case START_PARTITION:
      return isSetStartPartition();
    case SETUPS:
      return isSetSetups();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof StagingQuery)
      return this.equals((StagingQuery)that);
    return false;
  }

  public boolean equals(StagingQuery that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_metaData = true && this.isSetMetaData();
    boolean that_present_metaData = true && that.isSetMetaData();
    if (this_present_metaData || that_present_metaData) {
      if (!(this_present_metaData && that_present_metaData))
        return false;
      if (!this.metaData.equals(that.metaData))
        return false;
    }

    boolean this_present_query = true && this.isSetQuery();
    boolean that_present_query = true && that.isSetQuery();
    if (this_present_query || that_present_query) {
      if (!(this_present_query && that_present_query))
        return false;
      if (!this.query.equals(that.query))
        return false;
    }

    boolean this_present_startPartition = true && this.isSetStartPartition();
    boolean that_present_startPartition = true && that.isSetStartPartition();
    if (this_present_startPartition || that_present_startPartition) {
      if (!(this_present_startPartition && that_present_startPartition))
        return false;
      if (!this.startPartition.equals(that.startPartition))
        return false;
    }

    boolean this_present_setups = true && this.isSetSetups();
    boolean that_present_setups = true && that.isSetSetups();
    if (this_present_setups || that_present_setups) {
      if (!(this_present_setups && that_present_setups))
        return false;
      if (!this.setups.equals(that.setups))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMetaData()) ? 131071 : 524287);
    if (isSetMetaData())
      hashCode = hashCode * 8191 + metaData.hashCode();

    hashCode = hashCode * 8191 + ((isSetQuery()) ? 131071 : 524287);
    if (isSetQuery())
      hashCode = hashCode * 8191 + query.hashCode();

    hashCode = hashCode * 8191 + ((isSetStartPartition()) ? 131071 : 524287);
    if (isSetStartPartition())
      hashCode = hashCode * 8191 + startPartition.hashCode();

    hashCode = hashCode * 8191 + ((isSetSetups()) ? 131071 : 524287);
    if (isSetSetups())
      hashCode = hashCode * 8191 + setups.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(StagingQuery other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetMetaData()).compareTo(other.isSetMetaData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetaData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metaData, other.metaData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetQuery()).compareTo(other.isSetQuery());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuery()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.query, other.query);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetStartPartition()).compareTo(other.isSetStartPartition());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartPartition()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startPartition, other.startPartition);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSetups()).compareTo(other.isSetSetups());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSetups()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.setups, other.setups);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("StagingQuery(");
    boolean first = true;

    if (isSetMetaData()) {
      sb.append("metaData:");
      if (this.metaData == null) {
        sb.append("null");
      } else {
        sb.append(this.metaData);
      }
      first = false;
    }
    if (isSetQuery()) {
      if (!first) sb.append(", ");
      sb.append("query:");
      if (this.query == null) {
        sb.append("null");
      } else {
        sb.append(this.query);
      }
      first = false;
    }
    if (isSetStartPartition()) {
      if (!first) sb.append(", ");
      sb.append("startPartition:");
      if (this.startPartition == null) {
        sb.append("null");
      } else {
        sb.append(this.startPartition);
      }
      first = false;
    }
    if (isSetSetups()) {
      if (!first) sb.append(", ");
      sb.append("setups:");
      if (this.setups == null) {
        sb.append("null");
      } else {
        sb.append(this.setups);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StagingQueryStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public StagingQueryStandardScheme getScheme() {
      return new StagingQueryStandardScheme();
    }
  }

  private static class StagingQueryStandardScheme extends org.apache.thrift.scheme.StandardScheme<StagingQuery> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, StagingQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // META_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.metaData = new MetaData();
              struct.metaData.read(iprot);
              struct.setMetaDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // QUERY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.query = iprot.readString();
              struct.setQueryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // START_PARTITION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.startPartition = iprot.readString();
              struct.setStartPartitionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SETUPS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list26 = iprot.readListBegin();
                struct.setups = new java.util.ArrayList<java.lang.String>(_list26.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem27;
                for (int _i28 = 0; _i28 < _list26.size; ++_i28)
                {
                  _elem27 = iprot.readString();
                  struct.setups.add(_elem27);
                }
                iprot.readListEnd();
              }
              struct.setSetupsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, StagingQuery struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.metaData != null) {
        if (struct.isSetMetaData()) {
          oprot.writeFieldBegin(META_DATA_FIELD_DESC);
          struct.metaData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.query != null) {
        if (struct.isSetQuery()) {
          oprot.writeFieldBegin(QUERY_FIELD_DESC);
          oprot.writeString(struct.query);
          oprot.writeFieldEnd();
        }
      }
      if (struct.startPartition != null) {
        if (struct.isSetStartPartition()) {
          oprot.writeFieldBegin(START_PARTITION_FIELD_DESC);
          oprot.writeString(struct.startPartition);
          oprot.writeFieldEnd();
        }
      }
      if (struct.setups != null) {
        if (struct.isSetSetups()) {
          oprot.writeFieldBegin(SETUPS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.setups.size()));
            for (java.lang.String _iter29 : struct.setups)
            {
              oprot.writeString(_iter29);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StagingQueryTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public StagingQueryTupleScheme getScheme() {
      return new StagingQueryTupleScheme();
    }
  }

  private static class StagingQueryTupleScheme extends org.apache.thrift.scheme.TupleScheme<StagingQuery> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StagingQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMetaData()) {
        optionals.set(0);
      }
      if (struct.isSetQuery()) {
        optionals.set(1);
      }
      if (struct.isSetStartPartition()) {
        optionals.set(2);
      }
      if (struct.isSetSetups()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetMetaData()) {
        struct.metaData.write(oprot);
      }
      if (struct.isSetQuery()) {
        oprot.writeString(struct.query);
      }
      if (struct.isSetStartPartition()) {
        oprot.writeString(struct.startPartition);
      }
      if (struct.isSetSetups()) {
        {
          oprot.writeI32(struct.setups.size());
          for (java.lang.String _iter30 : struct.setups)
          {
            oprot.writeString(_iter30);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StagingQuery struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.metaData = new MetaData();
        struct.metaData.read(iprot);
        struct.setMetaDataIsSet(true);
      }
      if (incoming.get(1)) {
        struct.query = iprot.readString();
        struct.setQueryIsSet(true);
      }
      if (incoming.get(2)) {
        struct.startPartition = iprot.readString();
        struct.setStartPartitionIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list31 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.setups = new java.util.ArrayList<java.lang.String>(_list31.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem32;
          for (int _i33 = 0; _i33 < _list31.size; ++_i33)
          {
            _elem32 = iprot.readString();
            struct.setups.add(_elem32);
          }
        }
        struct.setSetupsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

