load("@rules_jvm_external//:specs.bzl", "maven")
load(":defs.bzl", "repo", "versioned_artifacts")

maven_repo = repo(
    name = "maven",
    pinned = False,
    artifacts = [
        "org.scala-lang.modules:scala-collection-compat_2.12:2.6.0",
        "org.scala-lang.modules:scala-collection-compat_2.13:2.6.0",
        "org.scala-lang.modules:scala-parser-combinators_2.13:2.4.0",
        "org.scala-lang.modules:scala-java8-compat_2.12:1.0.0",
        "org.scala-lang.modules:scala-java8-compat_2.13:1.0.0",
        "org.apache.thrift:libthrift:0.13.0",
        "org.scala-lang.modules:scala-parallel-collections_2.13:1.0.4",
        "org.apache.commons:commons-lang3:3.12.0",
        "org.apache.commons:commons-math3:3.6.1",
        versioned_artifacts("1.2.3", [
            "ch.qos.logback:logback-classic",
            "ch.qos.logback:logback-core",
        ]),
        "ch.qos.reload4j:reload4j:1.2.19",

        # JUnit
        "junit:junit:4.13.2",
        "com.novocode:junit-interface:0.11",
        "org.scalatestplus:mockito-3-4_2.12:3.2.10.0",
        "org.scalatestplus:mockito-3-4_2.13:3.2.10.0",
        "org.mockito:mockito-core:4.6.1",
        "org.mockito:mockito-scala_2.12:1.17.0",
        "org.mockito:mockito-scala_2.13:1.17.0",
        "org.scalatest:scalatest_2.12:3.2.15",
        "org.scalatest:scalatest_2.13:3.2.15",
        "org.scalatest:scalatest-shouldmatchers_2.12:3.2.15",
        "org.scalatest:scalatest-shouldmatchers_2.13:3.2.15",
        "org.scalatest:scalatest-matchers-core_2.12:3.2.15",
        "org.scalatest:scalatest-matchers-core_2.13:3.2.15",
        "org.scalactic:scalactic_2.12:3.2.15",
        "org.scalactic:scalactic_2.13:3.2.15",

        # Add other dependencies
        "org.apache.hadoop:hadoop-common:3.3.1",
        "com.typesafe.akka:akka-actor_2.12:2.6.18",
        "com.typesafe.akka:akka-stream_2.12:2.6.18",
        "org.slf4j:slf4j-api:1.7.30",
        "org.slf4j:slf4j-log4j12:1.7.30",
        "org.apache.logging.log4j:log4j-core:2.14.1",
        "org.apache.logging.log4j:log4j-api:2.14.1",
        "com.fasterxml.jackson.core:jackson-core:2.12.5",
        "com.fasterxml.jackson.core:jackson-annotations:2.12.5",
        "com.fasterxml.jackson.core:jackson-databind:2.12.5",
        "com.fasterxml.jackson.module:jackson-module-scala_2.12:2.12.5",
        "com.fasterxml.jackson.module:jackson-module-scala_2.13:2.12.5",
        "org.apache.httpcomponents:httpclient:4.5.13",
        "org.apache.httpcomponents:httpcore:4.4.14",
        "com.google.guava:guava:30.1-jre",
        "org.xerial:sqlite-jdbc:3.34.0",
        "com.yahoo.datasketches:sketches-core:0.13.4",
        "com.google.code.gson:gson:2.8.6",
        "commons-lang:commons-lang:2.6",
        "commons-io:commons-io:2.11.0",
        "com.github.ben-manes.caffeine:caffeine:2.8.5",
        "net.jodah:typetools:0.4.1",
        "org.rogach:scallop_2.12:4.0.1",
        "org.rogach:scallop_2.13:4.0.1",
        "org.json4s:json4s-jackson_2.12:3.6.12",
        "org.json4s:json4s-core_2.12:3.6.12",
        "org.json4s:json4s-native_2.12:3.6.12",
        "org.json4s:json4s-ast_2.12:3.6.12",
        "org.json4s:json4s-jackson_2.13:3.6.12",
        "org.json4s:json4s-core_2.13:3.6.12",
        "org.json4s:json4s-native_2.13:3.6.12",
        "org.json4s:json4s-ast_2.13:3.6.12",
        "com.datadoghq:java-dogstatsd-client:2.7",
        "com.esotericsoftware:kryo:5.6.2",
        "io.delta:delta-core_2.12:2.0.2",
        "io.delta:delta-core_2.13:2.0.2",
        "com.github.jnr:jnr-ffi:2.2.10",
        "org.apache.kafka:kafka-clients:3.7.1",
        "org.codehaus.janino:janino:3.0.9",
        "org.codehaus.janino:commons-compiler:3.0.9",
        "org.codehaus.jackson:jackson-core-asl:1.9.13",

        # Vertx dependencies
        "io.vertx:vertx-core:4.5.10",
        "io.vertx:vertx-web:4.5.10",
        "io.vertx:vertx-config:4.5.10",
        "io.vertx:vertx-codegen:4.5.10",
        "io.vertx:vertx-unit:4.5.10",
        "io.vertx:vertx-micrometer-metrics:4.5.10",
        "io.micrometer:micrometer-core:1.12.4",
        "io.micrometer:micrometer-registry-statsd:1.12.4",

        # Proto
        "com.google.protobuf:protobuf-java:3.21.7",

        # Flink
        versioned_artifacts("1.19.0", [
            "org.apache.flink:flink-clients",
            "org.apache.flink:flink-connector-files",
            "org.apache.flink:flink-connector-hive_2.12",
            "org.apache.flink:flink-csv",
            "org.apache.flink:flink-json",
            "org.apache.flink:flink-metrics-core",
            "org.apache.flink:flink-metrics-prometheus:jar",
            "org.apache.flink:flink-orc",
            "org.apache.flink:flink-parquet",
            "org.apache.flink:flink-protobuf",
            "org.apache.flink:flink-scala_2.12",
            "org.apache.flink:flink-sql-gateway-api",
            "org.apache.flink:flink-streaming-java",
            "org.apache.flink:flink-streaming-scala_2.12",
            "org.apache.flink:flink-table-api-java",
            "org.apache.flink:flink-table-planner_2.12",
            "org.apache.flink:flink-test-utils",
            "org.apache.flink:flink-streaming-java:jar:tests",
            "org.apache.flink:flink-metrics-dropwizard",
        ]),
        maven.artifact(
            group = "org.apache.flink",
            artifact = "flink-core",
            version = "1.19.0",
            classifier = "tests",
        ),
        maven.artifact(
            group = "org.apache.flink",
            artifact = "flink-runtime",
            version = "1.19.0",
            classifier = "tests",
        ),
        # MongoDB Scala Driver and dependencies
        "org.mongodb.scala:mongo-scala-driver_2.12:4.11.1",
        "org.mongodb.scala:mongo-scala-bson_2.12:4.11.1",
        "org.mongodb:mongodb-driver-core:4.11.1",
        "org.mongodb:bson:4.11.1",
        "org.mongodb:mongodb-driver-sync:4.11.1",
        "org.mongodb:mongodb-driver-reactivestreams:4.11.1",
        "org.reactivestreams:reactive-streams:1.0.4",
        "org.mongodb:mongodb-driver-reactivestreams:4.11.1",
        "org.reactivestreams:reactive-streams:1.0.4",
        "io.dropwizard.metrics:metrics-core:4.2.20",
    ],
    overrides = {
    },
)
