config_setting(
    name = "spark_2_4",
    define_values = {"spark_version": "2.4"},
)

config_setting(
    name = "spark_3_1",
    define_values = {"spark_version": "3.1"},
)

config_setting(
    name = "spark_3_2",
    define_values = {"spark_version": "3.2"},
)
