config_setting(
    name = "spark_3_1",
    define_values = {"spark_version": "3.1"},
)

config_setting(
    name = "spark_3_2",
    define_values = {"spark_version": "3.2"},
)

config_setting(
    name = "spark_3_5",
    define_values = {"spark_version": "3.5"},
)
