config_setting(
    name = "flink_1_16",
    define_values = {"flink_version": "1.16"},
)

config_setting(
    name = "flink_1_19",
    define_values = {"flink_version": "1.19"},
)

config_setting(
    name = "flink_2_0",
    define_values = {"flink_version": "2.0"},
)
